"""addImgsNewsColumn1

Revision ID: 17698330f951
Revises: 57a9f395e750
Create Date: 2023-10-09 23:35:20.832578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17698330f951'
down_revision: Union[str, None] = '57a9f395e750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_imgs', 'news_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('news_imgs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint('news_imgs_id_fkey', 'news_imgs', type_='foreignkey')
    op.create_foreign_key(None, 'news_imgs', 'news', ['news_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_imgs', type_='foreignkey')
    op.create_foreign_key('news_imgs_id_fkey', 'news_imgs', 'news', ['id'], ['id'])
    op.alter_column('news_imgs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('news_imgs', 'news_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
