"""addImgsNewsColumn

Revision ID: 57a9f395e750
Revises: 6c9921e36e31
Create Date: 2023-10-09 23:31:21.141874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a9f395e750'
down_revision: Union[str, None] = '6c9921e36e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_imgs', sa.Column('id', sa.Integer(), nullable=True))
    op.alter_column('news_imgs', 'news_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint('news_imgs_news_id_fkey', 'news_imgs', type_='foreignkey')
    op.create_foreign_key(None, 'news_imgs', 'news', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_imgs', type_='foreignkey')
    op.create_foreign_key('news_imgs_news_id_fkey', 'news_imgs', 'news', ['news_id'], ['id'])
    op.alter_column('news_imgs', 'news_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('news_imgs', 'id')
    # ### end Alembic commands ###
