"""addColMotoCar

Revision ID: 6c9921e36e31
Revises: c134e474ccac
Create Date: 2023-10-09 21:29:32.762923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9921e36e31'
down_revision: Union[str, None] = 'c134e474ccac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto_carousel', sa.Column('prev_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moto_carousel', 'prev_img')
    # ### end Alembic commands ###
