"""addTablesSpecColumn

Revision ID: 73062658e288
Revises: babfbc03bb46
Create Date: 2023-10-11 00:37:13.307865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73062658e288'
down_revision: Union[str, None] = 'babfbc03bb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keySpec', sa.Column('page', sa.String(), nullable=True))
    op.add_column('specData', sa.Column('page', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specData', 'page')
    op.drop_column('keySpec', 'page')
    # ### end Alembic commands ###
